<span id="wsbimg1">
<?php
$this->widget('application.extensions.videojs.EVideoJS', array(
    'options' => array(
        // Unique identifier, is autogenerated by default, useful for jQuery integrations.
        'id' => false,
        // Video and poster width in pixels
        'width' => 450,
        // Video and poster height in pixels
        'height' => 300,
        // Poster image absolute URL
        'poster' => Yii::app()->theme->baseUrl.'/images/Landscape.jpg',
        // Absolute URL of the video in MP4 format
        'video_mp4' => Yii::app()->baseUrl.'/videos/demo.mp4',
        // Absolute URL of the video in OGV format
        'video_ogv' => false,
        // Absolute URL of the video in WebM format
        'video_webm' => false,
        // Use Flash fallback player ?
        'flash_fallback' => true,
        // Address of custom Flash player to use as fallback
        'flash_player' => 'http://releases.flowplayer.org/swf/flowplayer-3.2.1.swf',
        // Show controls ?
        'controls' => true,
        // Preload video content ?
        'preload' => true,
        // Autostart the playback ?
        'autoplay' => false,
        // Show VideoJS support link ?
        'support' => false,
        // Show video download links ?
        'download' => false,
    ),
));
?>
</span>



<div id="wsbtxt2" class="heading1">
<p><?php echo Yii::t('translation', 'The Book of Professors &amp; Students All Over the World!'); ?>
</p></div>
<div id="wsbtxt3" class="heading-text"><p><span style="font-size: x-large;"><?php echo Yii::t('translation', 'What are you looking for?'); ?> </span></p></div>
<?php 
$btn_type_student=false;
$btn_type_professor=false;
if($controller->tag==ViewController::VIEW_PROFESSORS) 
{
	$btn_type_professor=true;
}
else
{
	$btn_type_student=true;
}

echo CHtml::link(Yii::t('translation', 'Professor'), 
		array('index', 'status'=>ViewController::VIEW_PROFESSORS),
		array('style'=>'position: absolute; left: 10px; top: 321px; width: 160px; z-index: 9; vertical-align:middle;font-size:28px;padding:14px;',
		'class'=>$btn_type_student ? 'black' : 'orange',
		'id'=>'btn-look-for-prof',
		)
	);
Yii::app()->getClientScript()->registerScript('style-btn-look-for-prof', '$("#btn-look-for-prof").corner("cc:#27659C round")', CClientScript::POS_READY);
	
echo CHtml::link(Yii::t('translation', 'Student'), 
		array('index', 'status'=>ViewController::VIEW_STUDENTS),
		array('style'=>'position: absolute; left: 230px; top: 322px; width: 160px; z-index: 10;vertical-align:middle; font-size:28px;padding:14px;',
		'class'=>$btn_type_professor ? 'black' : 'orange',
		'id'=>'btn-look-for-student',
		)
	);
Yii::app()->getClientScript()->registerScript('style-btn-look-for-student', '$("#btn-look-for-student").corner("cc:#27659C round")', CClientScript::POS_READY);
?>

<?php 
$btn_lang_english=false;
$btn_lang_chinese=false;
if(isset(Yii::app()->session['_lang']) && Yii::app()->session['_lang']==='zh_cn') 
{
	$btn_lang_chinese=true;
}
else
{
	$btn_lang_english=true;
}

echo CHtml::link(Yii::t('translation', 'Chinese'), 
		array('index', 'status'=>$controller->tag, 'language'=>'zh_cn'),
		array('style'=>'position: absolute; left: 310px; top: 70px; width:60px;height:20px; z-index: 10;',
		'class'=>$btn_lang_chinese ? 'orange' : 'black',
		'id'=>'btn-lang-chinese',
		)
	);
Yii::app()->getClientScript()->registerScript('style-btn-lang-chinese', '$("#btn-lang-chinese").corner("cc:#27659C  bottom")', CClientScript::POS_READY);
	
echo CHtml::link(Yii::t('translation', 'English'), 
		array('index', 'status'=>$controller->tag, 'language'=>'en_us'),
		array('style'=>'position: absolute; left: 380px; top: 70px; width:60px;height:20px; z-index: 10;',
		'class'=>$btn_lang_english ? 'orange' : 'black',
		'id'=>'btn-lang-english',
		)
	);
	
Yii::app()->getClientScript()->registerScript('style-btn-lang-english', '$("#btn-lang-english").corner("cc:#27659C bottom")', CClientScript::POS_READY);

$user=Yii::app()->accountMgr->getUser();
if(!isset($user))
{
	$this->beginWidget('zii.widgets.jui.CJuiDialog', array(
		'id'=>'login-dialog',
		'options'=>array(
			'title'=>Yii::t('translation', 'Login'),
			'autoOpen'=>false,
			'modal' => true,
			'resizable' => false,
			'width'=>'auto',
			'height'=>'auto',
		),
	));

	echo $this->renderPartial('_formLogin'); 
	$this->endWidget('zii.widgets.jui.CJuiDialog');
	
	echo CHtml::link(Yii::t('translation', 'Login'), 
		'#',
		array('style'=>'position: absolute; left: 240px; top: 70px; width:60px;height:20px; z-index: 10;',
		'onclick'=>'$("#login-dialog").dialog("open"); return false;',
		'class'=>'black',
		'id'=>'btn-login',
		)
	);
	
	Yii::app()->getClientScript()->registerScript('style-btn-login', '$("#btn-login").corner("cc:#27659C bottom")', CClientScript::POS_READY);
}
?>

